---
- name: create .ssh dir
  file:
    path: /var/lib/postgresql/.ssh
    state: directory
    group: postgres
    owner: postgres
    mode: 0700
- name: copy pub_key
  copy:
    src: id_rsa.pub
    dest: /var/lib/postgresql/.ssh/id_rsa.pub
    owner: postgres
    group: postgres
    mode: 0644
- name: copy priv_key
  copy:
    src: id_rsa
    dest: /var/lib/postgresql/.ssh/id_rsa
    owner: postgres
    group: postgres
    mode: 0600
- name: copy authorized_keys
  copy:
    src: authorized_keys
    dest: /var/lib/postgresql/.ssh/authorized_keys
    owner: postgres
    group: postgres
    mode: 0664
